# Generated by Django 5.1.4 on 2024-12-12 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('estatura_minima', models.FloatField()),
                ('condiciones_uso', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('estatura', models.FloatField()),
                ('edad', models.IntegerField()),
                ('contacto_familiar', models.CharField(blank=True, max_length=100, null=True)),
                ('publicidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('ADMIN', 'Administrativo'), ('LOG', 'Logística'), ('PUB', 'Publicidad'), ('OPE', 'Operador'), ('MANT', 'Mantenimiento')], max_length=5)),
                ('horario_laboral', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.atraccion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.cliente')),
            ],
        ),
    ]
