# Generated by Django 5.1.4 on 2024-12-14 01:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atraccion',
            name='estatura_minima',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='La estatura mínima debe ser positiva.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(110, message='Edad no válida.')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estatura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='La estatura debe ser positiva.')]),
        ),
        migrations.CreateModel(
            name='EstadoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Mantenimiento', 'Mantenimiento'), ('Averiada', 'Averiada')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='parque.atraccion')),
            ],
        ),
    ]
